project:
  type: website
  output-dir: docs

website:
  title: "AERA SIG93 Graduate Network"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: "Email List Subscription"
      - href: unsubscribe.qmd
        text: "Unsubscribe"
      - href: suggestions.qmd
        text: "Suggestions"
      - href: whoweare.qmd
        text: "Who we are"
  google-analytics: G-NCKE112EVM  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true