---
title: "Graduate Email List Subscription"
---
```{=html}
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSf7kw1lBMtzhAt3QXN0YV5E5f9xMhyY4AWydperbtQ8ibxyuw/viewform?embedded=true" width="100%" height="1896" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
```


# [AERA SIG93](https://www.aera.net/SIG093/RLIPE-SIG-93)
Research on Learning & Instruction in Physical Education

## Graduate Student Network
My name is [Yongjin Lee](https://yongjin-l.github.io), and I am the Graduate Representative for our SIG.

This network is being created to build a supportive community for graduate students studying physical education. **You do not need to be a current AERA or SIG93 member to join this network—all are welcome!**

Our main goal is to connect, share resources, and support one another on our academic journeys.

## What to Expect:

* **Monthly Online Meetups:** We will host a casual online meeting immediately following the monthly SIG93 webinars.
* **Networking & Support:** This will be a great chance to get to know your peers from other universities and build a strong support system.
* **Shape the Future:** Your ideas and discussions will directly influence the development of practical programming of our SIG. We will use your feedback to create a dedicated graduate student session within a future SIG93 monthly webinar and the Invisible College session at the AERA national conference.

Please fill out the short form below to be added to our emailing list. You'll receive updates on meeting times, links, and other network news. Please don't worry. You can unsubscribe from this email list at any time on the "[Unsubscribe](https://yongjin-l.github.io/AERA93-GradNetwork/unsubscribe.html)" page.

We are excited to build this community with you!